# Generated by Django 4.2.7 on 2026-06-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_logactividad_bien_logactividad_bien_clave_unica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienpatrimonial',
            name='origen',
            field=models.CharField(blank=True, choices=[('', 'Sin especificar'), ('COMPRA', 'Compra'), ('COMPRA_MENOR', 'Compra Menor'), ('DONACION', 'Donación'), ('TRANSFERENCIA', 'Transferencia'), ('OMISION', 'Omisión')], default='', max_length=15, verbose_name='Origen'),
        ),
    ]
